apiVersion: v1
kind: Service
metadata:
  name: play-barcode-dev
spec:
  type: ClusterIP
  selector:
    app: play-barcode-dev
  ports:
    - name: http
      port: 80 # 서비스의 80번 포트로 들어오면
      targetPort: 80 # Pod의 80번 포트로 전달
      protocol: TCP
    - name: https
      port: 443 # 서비스의 443번 포트로 들어오면
      targetPort: 80 # Pod의 80번 포트로 전달
      protocol: TCP
